# Configuration GitHub Pages pour le site de la Sira
title: "السيرة النبوية الشريفة - Vie du Prophète Muhammad ﷺ"
description: "Site web éducatif interactif sur la biographie du Prophète Muhammad ﷺ avec 15 périodes historiques basées sur des sources authentiques"
url: "https://elbachirmohamed33.github.io"
baseurl: "/sira-prophet-muhammad"

# Paramètres du site
lang: fr
locale: fr_FR

# SEO et métadonnées
author: "elbachirmohamed33"
keywords: "Islam, Prophète Muhammad, Sira, Biographie, Éducation islamique, Histoire islamique"

# Configuration Jekyll
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclusions
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - deploy_website.sh
  - deploy_website.ps1
  - deploy_website.bat

# Inclusion forcée pour GitHub Pages
include:
  - _config.yml
  - .nojekyll

# Configuration des collections (optionnel)
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      
# Thème (utilise le thème par défaut)
# Configuration pour GitHub Pages - Site de la Sira du Prophète Muhammad ﷺ

title: "السيرة النبوية الشريفة - Life of Prophet Muhammad ﷺ"
description: "Complete multilingual biography of Prophet Muhammad ﷺ in Arabic, French, and English"
baseurl: "/sira-prophet-muhammad"
url: "https://elbachimohamed33.github.io"

# GitHub Pages settings
theme: minima
markdown: kramdown
highlighter: rouge

# Supported languages
languages: [ar, fr, en]

# SEO settings
lang: ar
author: "Bachir Mohamed"

# PWA and analytics
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files
exclude:
  - "*.ps1"
  - "*.bat"
  - "*.sh"
  - README.md
  - node_modules/
  - vendor/
